############################################
# pipeline for predicting stock price with news
# set true to run the pipeline, false to skip the pipeline
[pipeline]

ingestion = true
feature = true
strategy = false
evaluation = false




############################################
[info]
# local path to store all data (change to your local path)
local_data_path = "/Users/xwpeng/Projects/Erdos_Finance_LLM_data"

# directories names for data files in the local "i.e., Google Drive" path
# data_raw: raw stock and news data
# data_clean: cleaned and processed stock and news data, which can be used for modeling directly
# model: all the models files
# feature: extracted features from the cleaned data
# stratergy: trading stratergies and action records
# evaluation: backtesting results
dirs_names = ["logs", "config_archive", "data_raw", "data_clean", "model", "feature", "stratergy", "evalulation"]

# Database settings
db_name = "stock_daily_data.db"




############################################
# parameters for each step in the pipeline
[ingestion]
start_date = "2015-01-01"
end_date = "2024-12-31"
stock_list = ["AAPL", "MSFT", "NVDA", "GOOG"]
news_symbols = ["AAPL", "MSFT", "NVDA", "GOOG"]

[feature]
# Technical analysis factors configuration
# trend: MA, EMA, MACD, ADX
# momentum: RSI, ROC, MOM
# volatility: BBANDS, CCI, ATR
# volume: OBV, AD

[feature.factor_parameters]
# momentum
rsi_6 = { timeperiod = 6 }
rsi_12 = { timeperiod = 12 }
rsi_24 = { timeperiod = 24 }

roc_14 = { timeperiod = 14 } 
roc_30 = { timeperiod = 30 }
roc_60 = { timeperiod = 60 }

mom_14 = { timeperiod = 14 } 
mom_30 = { timeperiod = 30 }
mom_60 = { timeperiod = 60 }

# trend
ma_20 = { timeperiod = 20 }
ma_30 = { timeperiod = 30 }
ma_60 = { timeperiod = 60 }
ma_200 = { timeperiod = 200 }

ema_20 = { timeperiod = 20 }
ema_30 = { timeperiod = 30 }
ema_60 = { timeperiod = 60 }
ema_200 = { timeperiod = 200 } 

macd = { fastperiod = 12, slowperiod = 26, signalperiod = 9 } # return 3 columns: macd, macd_signal, macd_hist

adx = { timeperiod = 14 }

# volatility
bbands = { timeperiod = 20, nbdevup = 2, nbdevdn = 2 } # return 3 columns: upper, middle, lower

cci = { timeperiod = 14 }

atr = { timeperiod = 14 }

# volume
obv = {} 

ad = {}

[strategy]

[evaluation]



############################################
# automatically generate when run the predic_stock_w_news.py
# for virsion control of files
[date]