############################################
# pipeline for predicting stock price with news
# set true to run the pipeline, false to skip the pipeline
[pipeline]

ingestion = true
feature = false
strategy = false
evaluation = false




############################################
[info]
# local path to store all data (change to your local path)
local_data_path = "/Users/xwpeng/Projects/Erdos_Finance_LLM_data"

# directories names for data files in the local "i.e., Google Drive" path
# data_raw: raw stock and news data
# data_clean: cleaned and processed stock and news data, which can be used for modeling directly
# model: all the models files
# feature: extracted features from the cleaned data
# stratergy: trading stratergies and action records
# evaluation: backtesting results
dirs_names = ["logs", "config_archive", "data_raw", "data_clean", "model", "feature", "stratergy", "evalulation"]

# Database settings
db_name = "stock_daily_data.db"

start_date = "2010-01-01"
end_date = "2013-12-31"



############################################
# parameters for each step in the pipeline
[ingestion]
stock_list = ["AAPL", "MSFT", "NVDA", "GOOG"]

# Technical analysis factors configuration
factors = ["RSI", "ROC", "MOM"]

[ingestion.factor_parameters]
RSI = { timeperiod = 14 }
ROC = { timeperiod = 10 }
MOM = { timeperiod = 10 }

[clean]

[feature]

[strategy]

[evaluation]



############################################
# automatically generate when run the predic_stock_w_news.py
# for virsion control of files
[date]